package com.polsl.android.employeetracker.Entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.polsl.android.employeetracker.Entity.User;
import com.polsl.android.employeetracker.Entity.LocationData;
import com.polsl.android.employeetracker.Entity.RouteData;
import com.polsl.android.employeetracker.Entity.FuelConsumptionRateData;
import com.polsl.android.employeetracker.Entity.FuelLevelData;
import com.polsl.android.employeetracker.Entity.OilTemperatureData;
import com.polsl.android.employeetracker.Entity.RPMData;
import com.polsl.android.employeetracker.Entity.SpeedData;
import com.polsl.android.employeetracker.Entity.TroubleCodesData;

import com.polsl.android.employeetracker.Entity.UserDao;
import com.polsl.android.employeetracker.Entity.LocationDataDao;
import com.polsl.android.employeetracker.Entity.RouteDataDao;
import com.polsl.android.employeetracker.Entity.FuelConsumptionRateDataDao;
import com.polsl.android.employeetracker.Entity.FuelLevelDataDao;
import com.polsl.android.employeetracker.Entity.OilTemperatureDataDao;
import com.polsl.android.employeetracker.Entity.RPMDataDao;
import com.polsl.android.employeetracker.Entity.SpeedDataDao;
import com.polsl.android.employeetracker.Entity.TroubleCodesDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig locationDataDaoConfig;
    private final DaoConfig routeDataDaoConfig;
    private final DaoConfig fuelConsumptionRateDataDaoConfig;
    private final DaoConfig fuelLevelDataDaoConfig;
    private final DaoConfig oilTemperatureDataDaoConfig;
    private final DaoConfig rPMDataDaoConfig;
    private final DaoConfig speedDataDaoConfig;
    private final DaoConfig troubleCodesDataDaoConfig;

    private final UserDao userDao;
    private final LocationDataDao locationDataDao;
    private final RouteDataDao routeDataDao;
    private final FuelConsumptionRateDataDao fuelConsumptionRateDataDao;
    private final FuelLevelDataDao fuelLevelDataDao;
    private final OilTemperatureDataDao oilTemperatureDataDao;
    private final RPMDataDao rPMDataDao;
    private final SpeedDataDao speedDataDao;
    private final TroubleCodesDataDao troubleCodesDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        locationDataDaoConfig = daoConfigMap.get(LocationDataDao.class).clone();
        locationDataDaoConfig.initIdentityScope(type);

        routeDataDaoConfig = daoConfigMap.get(RouteDataDao.class).clone();
        routeDataDaoConfig.initIdentityScope(type);

        fuelConsumptionRateDataDaoConfig = daoConfigMap.get(FuelConsumptionRateDataDao.class).clone();
        fuelConsumptionRateDataDaoConfig.initIdentityScope(type);

        fuelLevelDataDaoConfig = daoConfigMap.get(FuelLevelDataDao.class).clone();
        fuelLevelDataDaoConfig.initIdentityScope(type);

        oilTemperatureDataDaoConfig = daoConfigMap.get(OilTemperatureDataDao.class).clone();
        oilTemperatureDataDaoConfig.initIdentityScope(type);

        rPMDataDaoConfig = daoConfigMap.get(RPMDataDao.class).clone();
        rPMDataDaoConfig.initIdentityScope(type);

        speedDataDaoConfig = daoConfigMap.get(SpeedDataDao.class).clone();
        speedDataDaoConfig.initIdentityScope(type);

        troubleCodesDataDaoConfig = daoConfigMap.get(TroubleCodesDataDao.class).clone();
        troubleCodesDataDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        locationDataDao = new LocationDataDao(locationDataDaoConfig, this);
        routeDataDao = new RouteDataDao(routeDataDaoConfig, this);
        fuelConsumptionRateDataDao = new FuelConsumptionRateDataDao(fuelConsumptionRateDataDaoConfig, this);
        fuelLevelDataDao = new FuelLevelDataDao(fuelLevelDataDaoConfig, this);
        oilTemperatureDataDao = new OilTemperatureDataDao(oilTemperatureDataDaoConfig, this);
        rPMDataDao = new RPMDataDao(rPMDataDaoConfig, this);
        speedDataDao = new SpeedDataDao(speedDataDaoConfig, this);
        troubleCodesDataDao = new TroubleCodesDataDao(troubleCodesDataDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(LocationData.class, locationDataDao);
        registerDao(RouteData.class, routeDataDao);
        registerDao(FuelConsumptionRateData.class, fuelConsumptionRateDataDao);
        registerDao(FuelLevelData.class, fuelLevelDataDao);
        registerDao(OilTemperatureData.class, oilTemperatureDataDao);
        registerDao(RPMData.class, rPMDataDao);
        registerDao(SpeedData.class, speedDataDao);
        registerDao(TroubleCodesData.class, troubleCodesDataDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        locationDataDaoConfig.clearIdentityScope();
        routeDataDaoConfig.clearIdentityScope();
        fuelConsumptionRateDataDaoConfig.clearIdentityScope();
        fuelLevelDataDaoConfig.clearIdentityScope();
        oilTemperatureDataDaoConfig.clearIdentityScope();
        rPMDataDaoConfig.clearIdentityScope();
        speedDataDaoConfig.clearIdentityScope();
        troubleCodesDataDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public LocationDataDao getLocationDataDao() {
        return locationDataDao;
    }

    public RouteDataDao getRouteDataDao() {
        return routeDataDao;
    }

    public FuelConsumptionRateDataDao getFuelConsumptionRateDataDao() {
        return fuelConsumptionRateDataDao;
    }

    public FuelLevelDataDao getFuelLevelDataDao() {
        return fuelLevelDataDao;
    }

    public OilTemperatureDataDao getOilTemperatureDataDao() {
        return oilTemperatureDataDao;
    }

    public RPMDataDao getRPMDataDao() {
        return rPMDataDao;
    }

    public SpeedDataDao getSpeedDataDao() {
        return speedDataDao;
    }

    public TroubleCodesDataDao getTroubleCodesDataDao() {
        return troubleCodesDataDao;
    }

}
