package com.polsl.android.employeetracker.Entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.polsl.android.employeetracker.Entity.User;
import com.polsl.android.employeetracker.Entity.LocationData;
import com.polsl.android.employeetracker.Entity.RouteData;

import com.polsl.android.employeetracker.Entity.UserDao;
import com.polsl.android.employeetracker.Entity.LocationDataDao;
import com.polsl.android.employeetracker.Entity.RouteDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig locationDataDaoConfig;
    private final DaoConfig routeDataDaoConfig;

    private final UserDao userDao;
    private final LocationDataDao locationDataDao;
    private final RouteDataDao routeDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        locationDataDaoConfig = daoConfigMap.get(LocationDataDao.class).clone();
        locationDataDaoConfig.initIdentityScope(type);

        routeDataDaoConfig = daoConfigMap.get(RouteDataDao.class).clone();
        routeDataDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        locationDataDao = new LocationDataDao(locationDataDaoConfig, this);
        routeDataDao = new RouteDataDao(routeDataDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(LocationData.class, locationDataDao);
        registerDao(RouteData.class, routeDataDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        locationDataDaoConfig.clearIdentityScope();
        routeDataDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public LocationDataDao getLocationDataDao() {
        return locationDataDao;
    }

    public RouteDataDao getRouteDataDao() {
        return routeDataDao;
    }

}
