package com.polsl.android.employeetracker.entity;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ENGINE_LOAD".
*/
public class EngineLoadDao extends AbstractDao<EngineLoad, Void> {

    public static final String TABLENAME = "ENGINE_LOAD";

    /**
     * Properties of entity EngineLoad.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property RouteId = new Property(0, Long.class, "routeId", false, "ROUTE_ID");
        public final static Property Value = new Property(1, double.class, "value", false, "VALUE");
        public final static Property Timestamp = new Property(2, long.class, "timestamp", false, "TIMESTAMP");
    }

    private Query<EngineLoad> routeData_EngineLoadDataListQuery;

    public EngineLoadDao(DaoConfig config) {
        super(config);
    }
    
    public EngineLoadDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ENGINE_LOAD\" (" + //
                "\"ROUTE_ID\" INTEGER," + // 0: routeId
                "\"VALUE\" REAL NOT NULL ," + // 1: value
                "\"TIMESTAMP\" INTEGER NOT NULL );"); // 2: timestamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ENGINE_LOAD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EngineLoad entity) {
        stmt.clearBindings();
 
        Long routeId = entity.getRouteId();
        if (routeId != null) {
            stmt.bindLong(1, routeId);
        }
        stmt.bindDouble(2, entity.getValue());
        stmt.bindLong(3, entity.getTimestamp());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EngineLoad entity) {
        stmt.clearBindings();
 
        Long routeId = entity.getRouteId();
        if (routeId != null) {
            stmt.bindLong(1, routeId);
        }
        stmt.bindDouble(2, entity.getValue());
        stmt.bindLong(3, entity.getTimestamp());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public EngineLoad readEntity(Cursor cursor, int offset) {
        EngineLoad entity = new EngineLoad( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // routeId
            cursor.getDouble(offset + 1), // value
            cursor.getLong(offset + 2) // timestamp
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EngineLoad entity, int offset) {
        entity.setRouteId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setValue(cursor.getDouble(offset + 1));
        entity.setTimestamp(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(EngineLoad entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(EngineLoad entity) {
        return null;
    }

    @Override
    public boolean hasKey(EngineLoad entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "engineLoadDataList" to-many relationship of RouteData. */
    public List<EngineLoad> _queryRouteData_EngineLoadDataList(Long routeId) {
        synchronized (this) {
            if (routeData_EngineLoadDataListQuery == null) {
                QueryBuilder<EngineLoad> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.RouteId.eq(null));
                queryBuilder.orderRaw("T.'TIMESTAMP' ASC");
                routeData_EngineLoadDataListQuery = queryBuilder.build();
            }
        }
        Query<EngineLoad> query = routeData_EngineLoadDataListQuery.forCurrentThread();
        query.setParameter(0, routeId);
        return query.list();
    }

}
